### ISSUE TITLE
DOM errors because of vue-fragment

### ISSUE THREAD

**Issue by Sardor01** [Thunberg087/vue-fragment#62]
I think I'm having issues related to DOM in my app

![image](https://user-images.githubusercontent.com/58367523/110107265-7edac900-7dcc-11eb-9204-be59d9f4c00d.png)

**Comment by bgriggs1** [comment]
Same. Using v-show vs. v-if fixed a few cases, but it's pervasive for almost any reactive DOM updates.

**Comment by tomchiverton** [comment]
Duplicate of #61

**Comment by Sardor01** [comment]
> Duplicate of #61

It's not a duplicate; In https://github.com/Thunberg087/vue-fragment/issues/61 I addressed errors in new version of vue-fragment, but here I used vue-fragment v1.5.1 and still had issues related to DOM.

**Comment by Lionad-Morotar** [comment]
Same

**Comment by Tchoupinax** [comment]
Hello, 

Same issue met. Someone knows why ? 
The node to be removed is not a child of this node.

```
client.js?06a0:103 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Object.removeChild (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:5703:8)
    at removeNode (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:5874:15)
    at remove$$1 (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:5863:9)
    at removeAndInvokeRemoveHook (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:6150:9)
    at removeVnodes (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:6119:11)
    at updateChildren (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:6225:7)
    at patchVnode (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:6309:29)
    at VueComponent.patch [as __patch__] (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:6472:9)
    at VueComponent.Vue._update (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:3942:19)
    at VueComponent.updateComponent (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:4054:10)```

**Comment by BaileyJM02** [comment]
This is a duplicate of #32 and can be fixed without changing dependencies. (See #32)

@Sardor01, I believe you may have incorrectly altered your **package.json** file.
